fixtures:
  repositories:
    stdlib:      "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    java:        "https://github.com/puppetlabs/puppetlabs-java.git"
    wget:        "https://github.com/voxpupuli/puppet-wget.git"
  symlinks:
    artifactory: "#{source_dir}"
